[book]
authors = ["Mitchell Robert Vollger"]
language = "en"
multilingual = false
src = "src"
title = "The computational guide to Fiber-seq"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = false             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds


[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/fiberseq/fiberseq.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/fiberseq/fiberseq.github.io/edit/main/{path}"
mathjax-support = true


[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1        # the depth to start folding

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4

#[preprocessor.auto-links]
#command = "python auto-links.py"

[output.linkcheck]
optional = true # allows passing the github actions even if not installed
#follow-web-links = true
warning-policy = "warn"
